version: '3.8'

services:
  web:
    build: .
    expose:
      - 5000
    environment:
      - ENVIRONMENT=production
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    restart: always 