version: '3.8'

services:
  db:
    image: postgres:15
    container_name: buddy_postgres_prod
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-buddy}
      POSTGRES_USER: ${DATABASE_USER:-buddy}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-buddy} -d ${DATABASE_NAME:-buddy}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: buddy_app_prod
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://buddy:buddy@db:5432/buddy}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-buddy}
      - DATABASE_USER=${DATABASE_USER:-buddy}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DEFAULT_BUCKET_NAME=${DEFAULT_BUCKET_NAME}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_REALTIME_MODEL=${OPENAI_REALTIME_MODEL}
      - OPENAI_REALTIME_URL=${OPENAI_REALTIME_URL}
      - OPENAI_REALTIME_API_KEY=${OPENAI_REALTIME_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - SENTRY_DSN=${SENTRY_DSN}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data_prod: