[project]
name = "buddy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.38.18",
    "fastapi[standard]>=0.115.12",
    "openai>=1.79.0",
    "psycopg>=3.2.9",
    "tortoise-orm>=0.25.0",
]
