from dotenv import load_dotenv
import os

load_dotenv()

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION")
DEFAULT_BUCKET_NAME = os.getenv("DEFAULT_BUCKET_NAME")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
OPENAI_REALTIME_MODEL = os.getenv("OPENAI_REALTIME_MODEL")
OPENAI_REALTIME_URL = os.getenv("OPENAI_REALTIME_URL")
OPENAI_REALTIME_API_KEY = os.getenv("OPENAI_REALTIME_API_KEY")
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
SENTRY_DSN = os.getenv("SENTRY_DSN")
c
# Database Configuration
DATABASE_HOST = os.getenv("DATABASE_HOST", "db")
DATABASE_PORT = os.getenv("DATABASE_PORT", "5432")
DATABASE_NAME = os.getenv("DATABASE_NAME", "buddy")
DATABASE_USER = os.getenv("DATABASE_USER", "buddy")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD", "buddy")
DATABASE_URL = f"postgres://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"
